#!/usr/bin/env bash
# Generates Sources/WispCore/BuiltinInstructions.swift from Resources/AppInstructions/*.md.
# Each file becomes one entry keyed by its stem (file name without .md); the content is emitted as a
# Swift raw multi-line string literal so no escaping is needed. Output ordering is deterministic (C-locale sort).
# Usage: scripts/gen-instructions.sh
set -euo pipefail
cd "$(dirname "$0")/.."
SRC_DIR="Resources/AppInstructions"
OUT="Sources/WispCore/BuiltinInstructions.swift"

[ -d "$SRC_DIR" ] || { echo "gen-instructions: missing $SRC_DIR" >&2; exit 1; }

# Raw string delimiter: enough '#' so that neither the closing delimiter nor the raw escape ("\" + hashes)
# can occur inside the content.
delimiter_hashes() {
  local content="$1" n=1 hashes
  while :; do
    hashes=$(printf '%*s' "$n" '' | tr ' ' '#')
    if [[ "$content" != *"\"\"\"$hashes"* && "$content" != *"\\$hashes"* ]]; then
      printf '%s' "$hashes"
      return
    fi
    n=$((n + 1))
  done
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo "// GENERATED by scripts/gen-instructions.sh from Resources/AppInstructions/*.md. Do not edit by hand."
  echo "// swiftlint:disable all"
  echo
  echo "/// Built-in per-app instruction texts, keyed by stem (bundle id or a special key such as \`_browser\`)."
  echo "/// \`InstructionCatalog\` composes these with the user's own files under \`~/.config/wisp/instructions\`."
  echo "public enum BuiltinInstructions {"
  echo "    public static let text: [String: String] = ["
  count=0
  while IFS= read -r file; do
    stem=$(basename "$file" .md)
    content=$(cat "$file")   # command substitution strips trailing newlines
    hashes=$(delimiter_hashes "$content")
    printf '        %s"%s"%s: %s"""\n' "$hashes" "$stem" "$hashes" "$hashes"
    printf '%s\n' "$content"
    printf '"""%s,\n' "$hashes"
    count=$((count + 1))
  done < <(find "$SRC_DIR" -maxdepth 1 -name '*.md' -type f | LC_ALL=C sort)
  echo "    ]"
  echo "}"
} > "$tmp"
mv "$tmp" "$OUT"
echo "gen-instructions: wrote $OUT ($count entries)"
