// GENERATED by scripts/gen-instructions.sh from Resources/AppInstructions/*.md. Do not edit by hand.
// swiftlint:disable all

/// Built-in per-app instruction texts, keyed by stem (bundle id or a special key such as `_browser`).
/// `InstructionCatalog` composes these with the user's own files under `~/.config/wisp/instructions`.
public enum BuiltinInstructions {
    public static let text: [String: String] = [
        #"_browser"#: #"""
## Browser Computer Use

Open a new tab (cmd+t, or `wisp chrome new URL` for DevTools tabs) when you move to a different site or start an unrelated task. Stay in the current tab only if the user asked to continue there, or the page you are on is obviously the next step of the same workflow. This keeps the user's own pages intact.
"""#,
        #"chrome-tab"#: #"""
## Chrome tab (DevTools)

- Element indices refer to DOM-backed accessibility nodes. `set` writes an input's value and fires input/change events; `type` inserts text at the focus; `key` sends key events (Return submits forms).
- Navigate with `wisp chrome goto --tab T URL`. Do not `goto` the URL the tab already shows: it reloads and loses form state. Use `wisp chrome reload` when a reload is intended.
- A new site or separate task belongs in a new tab (`wisp chrome new URL`) unless the user asked to continue in this one.
- Tabs you open are ephemeral and are closed by `wisp end`. Keep a page that is the user's deliverable with `wisp chrome mark --tab T deliverable`, or a page where work continues later with `--tab T handoff`. Never mark research or intermediate tabs.
- File inputs: `wisp chrome upload --tab T --el <file input> /absolute/path` (no native panel opens). Uploads need the user's confirmation unless the user named the file and the site up front.
- JavaScript alerts and confirms block the page; the state header reports an open dialog and `wisp chrome dialog --tab T accept|dismiss` closes it.
- Screenshots are viewport pixels; `--at x,y` uses those pixels. Ask for `--screenshot` only when the tree lacks the context you need.
- Keep the browser in the background unless the user wants to watch; `wisp chrome show --tab T` brings it forward.
"""#,
        #"com.apple.MobileSMS"#: #"""
## Messages

Return in the composer sends immediately. Never send `wisp type` text containing newline characters to the composer, and never press Return without the user's confirmation for that message.

- Conversations are `row`s in the sidebar; the composer is the text field at the bottom (placeholder 'iMessage' or 'Text Message', inferred).
- Stage the message with `wisp set --app Messages --el <composer> 'text'`, run `wisp state --app Messages` to check the conversation and the text, get confirmation, then `wisp key --app Messages Return`.
- New conversation: cmd+n, type a name or number in the To field, pick the match from the suggestions, then Tab to the composer.
- Reactions, deleting conversations and read-receipt changes also need confirmation.
"""#,
        #"com.apple.Music"#: #"""
## Music

### Searching
- Click the 'Search' row in the sidebar, then `wisp set --app Music --el <search field> 'query'`; the search runs on its own. If results are not in the returned diff, run `wisp state --app Music` again.
- If the search row is not visible, scroll the sidebar to the top. The field revealed by the filter button (identifiers `filterBtn` / `filterField`) only filters the current view; it does not search the library or the catalog.
- To find a playlist, search with 'Your Library' selected in the results, or scroll the sidebar.

### Navigation
- Scroll lists with `wisp scroll --app Music --el <list> --down --pages 2`. When an element lists `{ScrollUp, ScrollDown}` actions, `wisp action --app Music --el N ScrollDown` works too. Batch several scroll steps with `wisp batch`.
- Selecting a sidebar item can drop you into a sub-view. Use the back button (identifier `backBtn`) to return to the root level.

### Playback
- Play a track with a double click: `wisp click --app Music --el N --double`.
- To queue a track ('Playing Next'), use the track's 'More' button and choose 'Play Next' or 'Play Last'. If no More button is exposed, right-click the track: `wisp click --app Music --el N --right`.
"""#,
        #"com.apple.Notes"#: #"""
## Notes

- Folders are a sidebar `outline`, notes a `table` of `row`s, the editor a `textarea`. New note: `wisp key --app Notes cmd+n`; the first line becomes the title.
- Search: cmd+option+f.
- Formatting shortcuts (Format menu): title cmd+shift+t, heading cmd+shift+h, body cmd+shift+b, checklist cmd+shift+l, bulleted list cmd+shift+7, dashed list cmd+shift+8, numbered list cmd+shift+9.
- Notes does not interpret Markdown. `wisp paste --app Notes --format html '<b>x</b>'` keeps formatting; `--format md` pastes rendered HTML with a plain-text fallback (inferred: the editor accepts the HTML pasteboard type).
- Deleting a note (cmd+delete) moves it to Recently Deleted; confirm first.
- Locked notes need the user's password: hand off.
"""#,
        #"com.apple.Safari"#: #"""
## Safari

### Address bar and tabs
- Focus the address field with `wisp key --app Safari cmd+l`, or `wisp set --app Safari --el <field named 'Address and Search'> 'https://example.com'` (field name as observed in earlier Wisp work), then `wisp key --app Safari Return`.
- Tabs are `tab` elements in the toolbar. cmd+t new tab, cmd+w close tab, cmd+shift+] / cmd+shift+[ next and previous tab, cmd+r reload, cmd+[ / cmd+] back and forward.
- Moving to another site or an unrelated task: open a new tab instead of reusing the current one, unless the user asked to continue there or the current page is clearly the next step of the same workflow.

### Page content
- Web content appears under the `web` node. Use `--query` to find controls on long pages and `wisp scroll --app Safari --el <web> --down` to move.
- If the `web` node is empty or the page is canvas-drawn, add `--screenshot` and click by pixels.
- Password AutoFill fields are secure fields; Wisp never reads or types into them. Hand logins to the user unless the user explicitly asked you to sign in to that site.
- Downloads: cmd+option+l shows the list. Uploads open a system Open panel: cmd+shift+g, type the absolute path, Return, then click Open. Confirm with the user before uploading.
"""#,
        #"com.apple.ScreenContinuity"#: #"""
## iPhone Mirroring

- The mirrored phone is a video stream: the window exposes no controls in the accessibility tree (inferred from the app's nature; verify with `wisp state --full`). Wisp attaches a window screenshot automatically when a tree has no actionable elements (Screen Recording permission required); request one explicitly with `wisp state --app 'iPhone Mirroring' --screenshot`.
- Click by pixels of that screenshot: `wisp click --app 'iPhone Mirroring' --at x,y --space screenshot`. Take a new screenshot after every action before choosing the next point.
- Keyboard shortcuts: `wisp key --app 'iPhone Mirroring' cmd+1` Home Screen, `cmd+2` App Switcher, `cmd+3` Spotlight.
- Scroll with `wisp scroll --app 'iPhone Mirroring' --at x,y --down`, not with `wisp drag`.
- On the Home Screen click the centre of an app icon, not its label.
"""#,
        #"com.apple.Terminal"#: #"""
## Terminal

Wisp's default policy denies Terminal (see the `deny` list in `wisp policy get`). If you already have a shell, run commands there instead of driving Terminal's window. Only when the user explicitly asks: `wisp policy set --allow com.apple.Terminal` (allow entries take precedence over deny entries).

- The window content is one `textarea` whose value is the screen buffer; read it with `wisp state --app Terminal --query 'text'`.
- `wisp type` followed by `wisp key Return` executes a command. Treat every command as irreversible and confirm before anything that changes state. ctrl+c cancels a running command; cmd+k clears the buffer.
"""#,
        #"com.apple.clock"#: #"""
## Clock

Supported tasks: add or remove World Clock cities; start, pause, resume and cancel a timer; start, stop, lap and reset the stopwatch; add, edit, remove, enable and disable alarms. Each area is a toolbar tab: click it first unless it is already selected.

### World Clock
1. Click the 'World Clock' tab.
2. Read the existing clocks from the container elements that have exactly one text child. Ignore everything under the 'world map' heading; it is not updated when clocks are removed.
3. If the city is missing, click the toolbar menu button described as 'Add a clock'.
4. In the sheet, `wisp set --app Clock --el <search field> 'City'`, then click the city's text; the city is added and the sheet closes.

### Timer
1. Click the 'Timer' tab and read the current state from the visible buttons.
2. If a timer is running or paused, tell the user and offer to cancel it before starting a new one.
3. Split the requested duration into hours (0-23), minutes (0-59) and seconds (0-59). Refuse anything longer than 23:59:59; the app cannot represent it.
4. Find the container identified as 'TimePicker'; its three sliders are hours, minutes and seconds, in that order.
5. For each slider: `wisp click --app Clock --el N` to focus it, then `wisp type --app Clock '30'` with at most two digits. Do not use `wisp set` on these sliders.
6. Click the button described as 'Start'.

### Stopwatch
Click the 'Stopwatch' tab. If the start/stop button reads 'Stop', the stopwatch is running: offer to stop or restart it. If it reads 'Start', click it.

### Alarm
1. Click the 'Alarm' tab, then the toolbar menu button described as 'Add an alarm'.
2. Set the time with `wisp set` on the date/time area, using the same format as its current value. Ignore the AM/PM radio buttons; they follow the value.
3. Repeat days are seven toggles labelled S M T W T F S; switch on the ones you need.
4. Label, sound and snooze have their own controls. Click 'Save'.
"""#,
        #"com.apple.dt.Xcode"#: #"""
## Xcode

- Prefer `xcodebuild`, `xcrun` and `swift` from a shell for builds and tests. Drive the UI only for things without a command line (simulator interaction, interface editors, signing dialogs).
- The tree is very large: always use `--query` and `--max-lines`. cmd+0 toggles the navigator, cmd+option+0 the inspector, cmd+shift+y the debug area, cmd+1 the project navigator, cmd+shift+o Open Quickly.
- The source editor is a `textarea`. Do not `wisp type` code into it: auto-indent and completion rewrite what is typed. Use `wisp select-text` to place the caret and `wisp paste --format text`, or edit the files on disk.
- cmd+b build, cmd+r run, cmd+. stop, cmd+shift+k clean.
- Signing and keychain prompts are secure dialogs: hand them to the user.
"""#,
        #"com.apple.finder"#: #"""
## Finder

Shortcuts below are the standard ones shown in Finder's menus; tree-structure notes are inferred from AppKit and should be checked with `wisp state --app Finder --full`.

### Navigation
- The sidebar is an `outline` of `row`s; the file area is a `table`/`outline` in list view or a group of icons in icon view. List view gives the most readable tree: `wisp key --app Finder cmd+2` (cmd+1 icons, cmd+3 columns, cmd+4 gallery).
- Go to a path: `wisp key --app Finder cmd+shift+g`, `wisp type --app Finder '/Users/me/Documents'`, `wisp key --app Finder Return`. Parent folder: cmd+up. Open the selection: cmd+down or `wisp click --el N --double`.
- Search the current folder: cmd+f, then `set` the search field.

### Files
- Rename: select the item, press Return, type the new name, press Return.
- New folder: cmd+shift+n. Get Info: cmd+i. Quick Look: space.
- Move to Trash: cmd+delete. Empty Trash: cmd+shift+delete. Deleting is an always-confirm action; emptying the Trash is irreversible. Moving or renaming files needs explicit approval too.
- Copy/paste: cmd+c then cmd+v; move instead of copy with cmd+option+v. Prefer these over `wisp drag`.

### Dialogs
Open and Save panels are separate windows drawn by a helper process; Wisp routes events to them automatically. Inside a panel, cmd+shift+g opens a path field.
"""#,
        #"com.apple.iCal"#: #"""
## Calendar

- Views: cmd+1 day, cmd+2 week, cmd+3 month, cmd+4 year; cmd+t today; cmd+r refresh.
- New event: cmd+n opens a quick-entry field; type a natural-language description (for example 'Lunch Friday 12pm') and press Return to create it. Double-click the event to open the editor: title and location are `field`s, dates and times are `datefield`/`timefield` controls (click a component such as hour or minute, type digits, Tab moves to the next component).
- Creating, editing or deleting events is an always-confirm action; the Delete key on a selected event removes it, so confirm first.
- Adding attendees sends invitations when the event is saved; confirm the attendee list before saving.
"""#,
        #"com.apple.iWork.Numbers"#: #"""
## Numbers

### Cells
- One click selects a cell; typing then appends (or fills an empty cell). A triple click (`wisp click --app Numbers --el N --triple`) selects the existing contents so typing replaces them.
- Enter a value in one round trip with `wisp batch --app Numbers`: a `click` step (count 1 or 3) followed by a `type` step.
- Enter a whole row at once by separating cells with tab characters in the typed text. Do not put several rows, or several formulas, in one `type` step; it fails.
- Values are stored immediately; Return is not needed to confirm a cell. Press it only when you are done with the sheet.
- Checkbox cells accept a typed `0` or `1`.

### Reading state
A focused cell may expose an extra 'text entry area' element carrying formatting artifacts (Markdown-style bold in header cells, for example); ignore it.
"""#,
        #"com.apple.mail"#: #"""
## Mail

### Layout
Mailboxes are a sidebar `outline`, messages a `table` of `row`s, and the message pane is rendered with WebKit (content under a `web` node). Search the mailbox with `wisp key --app Mail cmd+option+f`.

### Composing
- New message cmd+n; reply cmd+r; reply all cmd+shift+r; forward cmd+shift+f.
- To, Cc and Subject are `field`s; the body is a `textarea`. Return inside To commits the recipient token; it does not send.
- Send is cmd+shift+d or the Send button. Sending is outward-facing: fill everything, read the state to check recipients and text, and confirm with the user before sending.
- Long bodies: `wisp paste --app Mail --format md 'text'` for rich text or `--format text`.
- Attachments: the Attach toolbar button opens an Open panel (cmd+shift+g, path, Return, Open).

### Deleting and moving
The Delete key or cmd+delete moves the selected message to Trash; confirm before deleting.
"""#,
        #"com.apple.systempreferences"#: #"""
## System Settings

- Changing a system setting is an always-confirm action: read the current value, confirm with the user, then change it.
- Jump to a pane directly with a settings URL, then read it: `open 'x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility'` followed by `wisp state --app 'System Settings'`. Otherwise use the search field at the top of the sidebar.
- Sidebar entries are `row`s; panes use `switch`, `checkbox` and `popup` controls (inferred; verify with `--full`).
- Panes that ask for the user's password show a secure field; Wisp blocks it. Ask the user to unlock.
- Permission toggles for apps (Accessibility, Screen Recording, Full Disk Access) change security posture: confirm each one individually.
"""#,
        #"com.google.Chrome"#: #"""
## Google Chrome via accessibility

- For browser automation prefer `wisp chrome launch` and `--tab`: DOM-backed indices, proper input events, uploads and `wisp chrome eval`. Use this accessibility path only for the user's existing Chrome windows.
- Wisp enables Chrome's full accessibility tree on first read. If the page tree is empty, run `wisp state --app 'Google Chrome' --full` again.
- Address bar: cmd+l then type, or `set` the field named 'Address and search bar' (inferred from Chrome's omnibox label); Return navigates. cmd+t new tab, cmd+w close, cmd+shift+] / cmd+shift+[ switch tabs, cmd+r reload, cmd+[ / cmd+] back and forward.
- Web content is under the `web` node; canvas-heavy pages need `--screenshot` and pixel clicks.
- Uploads open a system Open panel: cmd+shift+g, absolute path, Return, Open. Confirm with the user first.
"""#,
        #"com.spotify.client"#: #"""
## Spotify

### The UI lags behind playback requests
Spotify updates its window a moment after a play or pause request, so the diff returned by a click may still show the previous track or a paused state. Do not click again: run `wisp state --app Spotify` and check; the change is usually visible by then. Do not add sleeps, Wisp already waits for the UI to settle.

### Search
Make sure the search field is the `focused` element before `wisp key --app Spotify Return`; a Return with nothing focused can start or stop playback. Prefer `wisp set --app Spotify --el <search field> 'query'` followed by Return.

### Network-backed views
Search results and lists come from the network. A momentary 'No results' is not final; re-read the state before changing approach.

### Links
Links copied from the app only work outside it as regular web links: use `https://open.spotify.com/...` addresses rather than `xpui.app.spotify.com` ones, and quote only links that appear verbatim in the state text.
"""#,
        #"com.tinyspeck.slackmacgap"#: #"""
## Slack

Slack is an Electron app. Wisp switches on its full accessibility tree the first time it reads it; if the first `wisp state --app Slack` looks empty, run `wisp state --app Slack --full` once more.

### The composer sends on Return
- When no text field is focused, typed text goes into the message composer. Before `wisp key --app Slack Return`, check in the latest state that the element you mean (search field, thread reply, edit box) is the one marked `focused`; otherwise Return may send a message.
- Prefer `wisp set --app Slack --el <composer> 'text'` over `wisp type` for the composer. `set` writes the value directly: a newline inside the value becomes a line break and nothing is sent. `wisp type` presses Return for every newline character, which sends the message in Slack's default configuration.
- `set` leaves Markdown syntax as literal characters. To convert it to Slack formatting afterwards, press `wisp key --app Slack cmd+shift+f` with the composer focused, then re-read the state.
- Sending is an outward-facing action: stage the text with `set`, read the state to confirm the composer shows exactly what you intend, and get the user's confirmation before pressing Return or clicking Send, unless the user already approved that specific message.

### Which key sends
Users can configure Slack so that either Return or Shift+Return sends. When the composer under a channel or direct message holds at least three characters, a button below it shows a hint of the form '<key combination> to add a new line'; the combination that is not mentioned is the one that sends. The hint is absent for thread replies and message edits. Find it with `wisp state --app Slack --query 'new line'`.

### When the tree misbehaves
If the accessibility text does not match what you expect (stale messages, missing composer), take `wisp state --app Slack --screenshot` and treat the picture as the source of truth; click by pixels with `--at x,y --space screenshot` when needed.
"""#,
        #"notion.id"#: #"""
## Notion

Notion's desktop app is Electron-based; Wisp enables its full accessibility tree on first read (re-run `wisp state --app Notion --full` if the first read is empty).

### Pages are blocks
- A page is a list of blocks. Clicking a block selects it; `wisp key --app Notion Return` starts editing the selected block's text.
- A new page has an empty title showing the placeholder 'New page'. Click the text element inside the heading to focus the title, `wisp type` the title, then press Return to move into the body.
- Enter body text one line per step: `wisp type --app Notion 'line'` then `wisp key --app Notion Return`. Put the alternating `type` and `key` steps in one `wisp batch --app Notion` call; do not send several lines in a single `type`.
- Markdown shortcuts apply while typing (`#` headings, `-` bullets, `**bold**`) with two differences: a leading `>` creates a toggle block, and a leading `|` creates a quote block.

### Lists
Return at the end of a list item creates the next item with its bullet already in place, so type only the text. Return on an empty list item ends the list.

### Selection: cmd+a depends on context
- Caret in an empty block: selects every block on the page.
- Caret in a non-empty block: selects that block's content; pressing cmd+a again selects every block.

### Placeholders
Empty elements show placeholder text: 'New page' (title), 'List' (list item), 'To-do' (checklist item), 'Write, ...' (empty line). Typing replaces it; never try to select and delete it.

### Code and quote blocks
In a code block Return adds a line inside the block and Shift+Return leaves it. Quote blocks are the reverse: Return leaves, Shift+Return stays inside.

### Moving the caret
- Top or bottom of the page: focus the document, press cmd+a twice, then Up or Down, then Return to edit the first or last block.
- A specific block: cmd+a twice, then click that block once.
- Or `wisp key --app Notion cmd+f`, type the text to find, press Escape: the match stays selected and becomes the caret position.
"""#,
    ]
}
